# Generated by Django 4.2.7 on 2024-01-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
