# Generated by Django 4.2.7 on 2024-01-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
