# Generated by Django 4.2.7 on 2024-01-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_booking_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='quantity_available',
            field=models.IntegerField(),
        ),
    ]
